# Use the official Node.js image
FROM node:14 as build

# Set the working directory within the container
WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

RUN npm run build

FROM node:14-alpine

WORKDIR /app/frontend

COPY --from=build /app/frontend/build ./build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build", "-l", "3000"]
