# Use the official Node.js image
FROM node:14

# Set the working directory within the container
WORKDIR /app/backend

# Copy the package.json and package-lock.json files to the container
COPY backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the backend code to the container
COPY backend/ ./

# Expose the port that your backend app will run on
EXPOSE 5000

# Command to run your backend app
CMD ["npm", "start"]
